import type { Metadata } from "next";
import "@/css/style.css";
import "@/css/fonts.css";
import "@/css/globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <div className="max-w-[440px] relative mx-auto">
            {children}
        </div>
      </body>
    </html>
  );
}
